<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="1" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-04-06T11:50:58 IST" name="Default suite" finished-at="2023-04-06T11:52:33 IST" duration-ms="95378">
    <groups>
    </groups>
    <test started-at="2023-04-06T11:50:58 IST" name="Default test" finished-at="2023-04-06T11:52:33 IST" duration-ms="95378">
      <class name="testcase.ExtentReportsTestcase">
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:testcase.ExtentReportsTestcase@79c97cb]" started-at="2023-04-06T11:50:58 IST" name="beforeTest" finished-at="2023-04-06T11:50:58 IST" duration-ms="157" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method is-config="true" signature="setup()[pri:0, instance:testcase.ExtentReportsTestcase@79c97cb]" started-at="2023-04-06T11:50:59 IST" name="setup" finished-at="2023-04-06T11:51:08 IST" duration-ms="9120" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="login(java.lang.String,java.lang.String)[pri:0, instance:testcase.ExtentReportsTestcase@79c97cb]" started-at="2023-04-06T11:51:08 IST" name="login" data-provider="testdata" finished-at="2023-04-06T11:51:21 IST" duration-ms="12490" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[demoflash294@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Thesnirav@14021996]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[demoflash294@gmail.com Username is wrong or Password field is not visible]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: demoflash294@gmail.com Username is wrong or Password field is not visible
at org.testng.Assert.fail(Assert.java:110)
at testcase.ExtentReportsTestcase.login(ExtentReportsTestcase.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcase.ExtentReportsTestcase@79c97cb]" started-at="2023-04-06T11:51:21 IST" name="tearDown" finished-at="2023-04-06T11:51:21 IST" duration-ms="291" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:testcase.ExtentReportsTestcase@79c97cb]" started-at="2023-04-06T11:51:21 IST" name="setup" finished-at="2023-04-06T11:51:29 IST" duration-ms="7529" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="login(java.lang.String,java.lang.String)[pri:0, instance:testcase.ExtentReportsTestcase@79c97cb]" started-at="2023-04-06T11:51:29 IST" name="login" data-provider="testdata" finished-at="2023-04-06T11:51:42 IST" duration-ms="13011" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[demoflash29@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Thesnirav@14021996]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[demoflash29@gmail.com Username is wrong or Password field is not visible]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: demoflash29@gmail.com Username is wrong or Password field is not visible
at org.testng.Assert.fail(Assert.java:110)
at testcase.ExtentReportsTestcase.login(ExtentReportsTestcase.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcase.ExtentReportsTestcase@79c97cb]" started-at="2023-04-06T11:51:42 IST" name="tearDown" finished-at="2023-04-06T11:51:42 IST" duration-ms="282" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:testcase.ExtentReportsTestcase@79c97cb]" started-at="2023-04-06T11:51:42 IST" name="setup" finished-at="2023-04-06T11:51:50 IST" duration-ms="7706" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="login(java.lang.String,java.lang.String)[pri:0, instance:testcase.ExtentReportsTestcase@79c97cb]" started-at="2023-04-06T11:51:50 IST" name="login" data-provider="testdata" finished-at="2023-04-06T11:52:02 IST" duration-ms="12725" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[demoflash25@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Thesnirav@14021996]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[demoflash25@gmail.com Username is wrong or Password field is not visible]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: demoflash25@gmail.com Username is wrong or Password field is not visible
at org.testng.Assert.fail(Assert.java:110)
at testcase.ExtentReportsTestcase.login(ExtentReportsTestcase.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcase.ExtentReportsTestcase@79c97cb]" started-at="2023-04-06T11:52:02 IST" name="tearDown" finished-at="2023-04-06T11:52:02 IST" duration-ms="233" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup()[pri:0, instance:testcase.ExtentReportsTestcase@79c97cb]" started-at="2023-04-06T11:52:02 IST" name="setup" finished-at="2023-04-06T11:52:10 IST" duration-ms="7261" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="login(java.lang.String,java.lang.String)[pri:0, instance:testcase.ExtentReportsTestcase@79c97cb]" started-at="2023-04-06T11:52:10 IST" name="login" data-provider="testdata" finished-at="2023-04-06T11:52:33 IST" duration-ms="23200" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[demoflash295@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Thesnirav@14021996]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testcase.ExtentReportsTestcase@79c97cb]" started-at="2023-04-06T11:52:33 IST" name="tearDown" finished-at="2023-04-06T11:52:33 IST" duration-ms="286" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcase.ExtentReportsTestcase -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
